-- Run this once in Supabase SQL Editor.
create table if not exists public.qb_editions (
  id bigint generated by default as identity primary key,
  week integer not null,
  publish_date date not null,
  players jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.qb_editions enable row level security;

create policy "Public can read editions" on public.qb_editions
for select using (true);

create policy "Authenticated users can insert editions" on public.qb_editions
for insert to authenticated with check (true);

-- Optional: restrict inserts to your own email by replacing the policy above with:
-- create policy "Only my account can insert" on public.qb_editions
-- for insert to authenticated with check ((select auth.jwt()->>'email') = 'YOUR_EMAIL');
